apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-of-object-detection-2 
  janus-idp.io/tekton: test-of-object-detection-2
  backstage.io/kubernetes-id: test-of-object-detection-2
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-of-object-detection-2
resources: 
- application-dev.yaml