apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-of-object-detection-2
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/gabemontero-appstudio-test-org/test-detr-2:d2c7d95fcad1e4c6640a8c9990fe98c91e373ad2@sha256:dd754110c26f227ce89226ee14d5057696edfb7953a22453dfebfc4830a6eeae # use pre-built to bootstrap 
          name: app-inference
